name: third_eye
description: "A new Flutter project for self-monitoring or controlled use."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  get: 4.7.2
  permission_handler: 12.0.1
  path: ^1.9.1
  path_provider: 2.1.5
  mailer: 6.5.0
  flutter_screenutil: 5.9.3
  flutter_screen_recording: 2.0.24
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: 0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/image/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/image/app_icon.png"
  min_sdk_android: 24

flutter:
  uses-material-design: true

  assets:
    - assets/image/